### ISSUE TITLE
User-can-view-home-screen

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/ajax-project#1]
## 💰 Motivation
If people are having a rough time, they can laugh at a terrible dad joke! If people are looking for inspiration or motivation, they can view popular quotes to get them going! 

## 📐 Plan
Create an Application that can brighten your mood or help motivate you.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/76730244/108782790-415b7d80-753a-11eb-9fc7-638acd84c46a.png)

## ✅ Task List
- [x] Create HTML Skeleton
- [x] Create Header element and add text
- [x] Create Logo Container and Add Image
- [x] Create Motivate Button
- [x] Create Laugh Button
- [x] Create Navigation Bar
- [x] Add Icons to Navigation Bar
- [x] Add styling to each element -- "Mobile First"
- [x] Animate elements into frame on load
- [x] Review styling and remove declarations that are not doing anything
