### ISSUE TITLE
User-can-view-motivational-quote

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/ajax-project#2]
## 💰 Motivation

If a user decides that they need a little motivation, they can click "Motivate" and see an inspirational quote.

## 📐 Plan

Allow users to view motivational/inspirational quotes.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76730244/108889204-1aed1f00-75da-11eb-890a-ad34ed6b9daf.png)

## ✅ Task List

- [x] Create a DIV to contain the UL and LI elements
- [x] Style the DIV element just like the wireframe
- [x] Add an un-ordered list element
- [x] Add an eventListener to the Motivate button that will hide the logo
- [x] Query the DOM for the UL element
- [x] Create a function that will pull random motivational quotes from an API
- [x] Create a function that will  create a DOM
- [x] Add the motivational quote text content to an LI element and append the LI element to the UL element
- [x] Add the author of the quote to the text content to an LI element and append the LI element to the UL element
- [x] Remove previous quote being shown and only display the newly generate Quote.
- [x] Add functionality to the eventListener to the Motivate button
- [x] Test functionality
- [x] Remove any unnecessary CSS Declarations that aren't doing anything
- [x] Fix all errors.
