### ISSUE TITLE
User-can-view-dad-joke

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/ajax-project#3]
## 💰 Motivation

If a user decides they would like to have a laugh, we're going to randomly generate a Dad Joke!

## 📐 Plan

Allow users to view funny dad jokes!

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76730244/108929139-7be41980-7611-11eb-87f0-f89644183f5e.png)

## ✅ Task List

- [x] Edit styling for the text container to better fit the texts
- [x] Add an eventListener to the Laugh button that will hide the logo
- [x] Query the DOM for the UL element
- [x] Create a function that will pull random Dad Jokes from an API
- [x] Call the dad joke function in the JS file
- [x] Create a function that will  create a DOM
- [x] Add the dad joke text content to an LI element and append the LI element to the UL element
- [x] Remove previous joke being shown and display the new joke
- [x] Add the dad joke function to the eventListener
- [x] Test functionality
- [x] Remove any unnecessary CSS Declarations that aren't doing anything
- [x] Fix all errors.
