### ISSUE TITLE
User-can-favorite-motivational-quote

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/ajax-project#4]
## 💰 Motivation

If a user decides that they like a motivational quote more than others, they can save them and view them seperately!

## 📐 Plan

Users can save their favorite motivational quotes!

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76730244/109039253-93b3b000-769a-11eb-8000-27c6f3cc3785.png)
![image](https://user-images.githubusercontent.com/76730244/109040610-1a1cc180-769c-11eb-83dc-35bc08b148e9.png)

## ✅ Task List

- [x] Create functionality for the Home Icon to bring users back to the Home Screen
- [x] Create a new DIV and UL for Favorited Quotes
- [x] Add functionality to Home Icon to hide these elements
- [x] Create a Favorite Icon and place them above the Motivate and Laugh buttons
- [x] Add functionality to the Favorite Icon to save the current text values and store them in JSON 
- [x] Add functionality to save the Favorited Quote in JSON
- [x] Test the functionality
- [x] Add functionality to display the Favorited Texts on the Quote Icon
- [x] Add functionality to update the header text when the user clicks the Quote Icon
- [x] Style the new DIV and UL to cover all the way to where the buttons ended
- [x] Add a scroll wheel to the DIV so the user can scroll to see all favorited Motivational Quotes
- [x] Test all functionality
- [x] Fix Errors
- [x] Remove any CSS Declarations that aren't doing anything
