### ISSUE TITLE
User-can-favorite-dad-joke

### ISSUE THREAD

**Issue by owen-adams2021** [owen-adams2021/ajax-project#5]
## 💰 Motivation

If a user decides that they like a Dad Joke more than others, they can save them and view them seperately!

## 📐 Plan

Users can save their favorite Dad Jokes!

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/76730244/109202248-c4feaf80-7770-11eb-9d30-4953521aabc9.png)

## ✅ Task List

- [x] Query the DOM for elements you will be using and updating
- [x] Add functionality to the Laugh button to display Favorite Icon
- [x] Add functionality to the Favorite Icon to push jokes into an array
- [x] Create functionality for Local Storage to stringify favorited jokes
- [x] Create functionality to parse from Local Storage for Favorited Jokes
- [x] Add functionality to update Header Text Contents when viewing Favorited Jokes
- [x] Add functionality to the Laugh Icon so users can view their Favorited Jokes
- [x] Test all functionality
- [x] Fix all errors
- [x] Remove any CSS Declarations that are not doing anything
